---
- name: Install apache2
  ansible.builtin.package:
    name: apache2
    state: latest

- name: Copy apache2.conf
  ansible.builtin.copy:
    src: '{{ var1 }}'
    dest: /etc/apache2/apache2.conf

- name: Copy index.html
  ansible.builtin.copy:
    src: '{{ var2 }}'
    dest: /var/www/html/index.html
- name: Create symbolic link for enabling site
  file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-available/headers.load
    state: link
    force: yes
