---
- hosts: all
  become: yes
  become_method: sudo
#  tasks:
#    - name: 'Task 1, Update APT'
#       ansible.builtin.apt:
#        update_cache: true
#    - name: 'Task 2, Install python-apt'
#      ansible.builtin.package:
#        name: python-apt
#        state: latest
#    - name: 'Task 3, Install apache2'
#      ansible.builtin.package:
#        name: apache2
#        state: latest
#    - name: 'Task 4, Copy apache2.conf'
#      ansible.builtin.copy:
#        src: /home/reveletheridge/raetheridg42-csc2510-infrastructure/apache2.conf
#        dest: /home/raetheridg42-csc2510-infrastructure/files/config/
#    - name: 'Task 5, Copy index.html'
#      ansible.builtin.copy:
#        src: /home/reveletheridge/raetheridg42-csc2510-infrastructure/index.html
#        dest: /home/reveletheridge/raetheridg42-csc2510-infrastructure/files/site/
#    - name: 'Task 6, Create symbolic link'
#      ansible.builtin.copy:
#        src: /home/reveletheridge/raetheridg42-csc2510-infrastructure/index.html
#        dest: /home/reveletheridge/raetheridg42-csc2510-infrastructure/files/site/
#        state: link
#    - name: 'Task 7, Restart apache2'
#      ansible.builtin.service:
#        name: apache2
#        state: restarted

