---
- hosts: all
  become: yes
  become_method: sudo
  tasks: 
  - name: Task 1, Update APT
    ansible.builtin.apt:
       update_cache: true
     
  - name: Task 2a, Install python-apt
    ansible.builtin.package:
     name: python-apt
     state: latest
       
  - name: Task 2b, Install apache2
    ansible.builtin.package:
        name: apache2
        state: latest
      
  - name: Task 3, Create symbolic link
        src: /etc/apache2/mods-available/headers/load
        dest: /etc/apache2/mods-enabled/headers/load
        state: link
  
  - name: Task 4, Restart apache2
    ansible.builtin.service:
          name: apache2
          state: restarted

